
spring:
  application:
    name: tm-service
  datasource:
    url: jdbc:mysql://localhost/compro
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
        properties:
          hibernate:
            jdbc:
              time_zone: UTC
server:
  port: 8002
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost