
spring:
  application:
    name: tm-service
  datasource:
    url: jdbc:mysql://localhost/comproTM
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8002